# lapa-casa-hostel/render.yaml

services:
  # Backend API Service
  - type: web
    name: lapa-casa-hostel-api
    env: node
    region: oregon
    plan: starter
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: lapa-casa-hostel-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: https://lapa-casa-hostel-frontend.onrender.com
      - key: TIMEZONE
        value: America/Sao_Paulo
    autoDeploy: true

  # Frontend Service
  - type: web
    name: lapa-casa-hostel-frontend
    env: static
    region: oregon
    plan: starter
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://lapa-casa-hostel-api.onrender.com
      - key: NODE_ENV
        value: production
    autoDeploy: true

# Database
databases:
  - name: lapa-casa-hostel-db
    databaseName: lapacasa
    user: lapacasa_user
    plan: starter
    region: oregon

# ✅ Archivo render.yaml completado
