# lapa-casa-hostel/infrastructure/kubernetes/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: lapa-app-service
  namespace: lapa-casa-hostel
  labels:
    app: lapa-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: lapa-app
  ports:
  - name: frontend
    port: 80
    targetPort: 3000
    protocol: TCP
  - name: backend
    port: 4000
    targetPort: 4000
    protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: lapa-casa-hostel
  labels:
    app: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP
  clusterIP: None

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: lapa-casa-hostel
  labels:
    app: redis
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lapa-ingress
  namespace: lapa-casa-hostel
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/rate-limit: "100"
spec:
  tls:
  - hosts:
    - lapacasahostel.com
    - www.lapacasahostel.com
    - api.lapacasahostel.com
    secretName: lapa-tls-cert
  rules:
  - host: lapacasahostel.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lapa-app-service
            port:
              number: 80
  - host: www.lapacasahostel.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lapa-app-service
            port:
              number: 80
  - host: api.lapacasahostel.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lapa-app-service
            port:
              number: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: lapa-casa-hostel
spec:
  type: ClusterIP
  selector:
    app: prometheus
  ports:
  - name: prometheus
    port: 9090
    targetPort: 9090
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: lapa-casa-hostel
spec:
  type: LoadBalancer
  selector:
    app: grafana
  ports:
  - name: grafana
    port: 80
    targetPort: 3000
    protocol: TCP

✅ Archivo 174/180 completado
